
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CADENA = 3;
  public static final int DECIMAL = 4;
  public static final int DOSPUNTOS = 6;
  public static final int ENTERO = 2;
  public static final int MENORQUE = 8;
  public static final int R_DOUBLE = 11;
  public static final int EOF = 0;
  public static final int RESERVADA_END = 10;
  public static final int VAR = 5;
  public static final int GUION = 9;
  public static final int error = 1;
  public static final int PUNTOYCOMA = 7;
  public static final int R_CHAR = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "CADENA",
  "DECIMAL",
  "VAR",
  "DOSPUNTOS",
  "PUNTOYCOMA",
  "MENORQUE",
  "GUION",
  "RESERVADA_END",
  "R_DOUBLE",
  "R_CHAR"
  };
}

