// ------------  Paquete e importaciones ------------
package DataForge_;

import java_cup.runtime.*;
import java.util.LinkedList;


//------> Codigo para el parser
//------> Declaracion de variables, funciones y funciones de error

parser code 
{:
    public static String resultado = ""; 

    public void syntax_error(Symbol s)
    {
            funciones.reportes.TablaErroresDF((String)s.value, "Error Sintáctico", s.right, s.left);
            System.err.println("Error Sintactico: "+ s.value + " - Fila: " + s.right + " - Columna: " + s.left + ". Recuperado" );
    }

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
    {
            funciones.reportes.TablaErroresDF((String)s.value, "Error Sintáctico", s.right, s.left);
            System.err.println("Error Sintactico: "+ s.value + " - Fila: " + s.right + " - Columna: " + s.left + ". Sin recuperacion." );
    }

:}


//------> Codigo para las acciones gramaticales (no tocar)
action code
{:  :}


//------> Declaración de terminales
terminal String PARENTESIS_A, PARENTESIS_C, PUNTOYCOMA,COMA;
terminal String SUM, RES,MUL,DIV, MOD;
terminal String POR, MAS,MENOS;
terminal String R_MOSTRAR;
terminal String ENTERO;
terminal String DECIMAL,CADENA;
terminal String PROGRAM;
terminal String END;
terminal String DOSPUNTOS;
terminal String VAR;
terminal String MENORQUE,MAYORQUE;
terminal String ARROBA;
terminal String CORCHETE_ABRE;
terminal String CORCHETE_CIERRA;
terminal String R_DOUBLE;
terminal String R_CHAR;
terminal String ARR;
terminal String MEDIA;
terminal String MEDIANA;
terminal String MODA;
terminal String VARIANZA;
terminal String MAX;
terminal String MIN;
terminal String PRINT;
terminal String COLUMN;
terminal String EXEC;
terminal String TITULO;
terminal String VALUES;
terminal String LABEL;
terminal String EJEX;
terminal String EJEY;
terminal String GRAPPIE;
terminal String GRAPHPIE;
terminal String GRAPHBAR;
terminal String GRAPHLINE;
terminal String HISTOGRAM;
terminal String CONSOLE;
terminal String TITULOX,TITULOY;
terminal String IDENTIFICADOR;
terminal String GUION;
terminal String IGUAL;
terminal String GRAPBAR;
terminal String GRAPLINE;
//------> Declaración de no terminales
non terminal inicio;
non terminal expresion;
non terminal tipodedato;
non terminal declaracion;
non terminal tipodegrafica;
non terminal declaracionhistograma;
non terminal declaracionbarras;
non terminal declaracionpie;
non terminal contenidopie;
non terminal declaracionlinea;
non terminal tipodato;
non terminal recorrido;
non terminal instrucciones;
non terminal arreglos;
non terminal operaciones;
non terminal operacion;
non terminal elementos;
non terminal elementospie;
non terminal valor;
non terminal valorpie;
non terminal datoslabel;
non terminal elementoslabel;
non terminal instrucciongrafica;
non terminal buclegrafica;
non terminal funcionesgrafica;
non terminal instruccionhistograma;
non terminal contenidohistograma;
non terminal elementoshistograma;
non terminal valorhistograma;
non terminal instruccionbarras; 
non terminal contenidobarras;
non terminal elementosejey;
non terminal valory;
non terminal elementosejex;
non terminal datox;
non terminal instruccionlinea;
non terminal contenidolinea;
non terminal elementoslinea;
non terminal valorlinea;
non terminal elementoslineac;
non terminal datoslineac;
non terminal valorexpresion;
non terminal operacionesnest;
non terminal arregloexpresiones;
non terminal printarreglos;
non terminal printexpresiones;
non terminal nt;
non terminal ntexp;
non terminal ciclo;
non terminal datosgraficas;
//------> PRECEDENCIA
precedence left MAS;
precedence left MENOS;
precedence left POR;


//------> Definir Simbolo Inicial
start with inicio; 


// ------------>  Producciones  <------------

inicio ::= PROGRAM recorrido END PROGRAM {::}
;

recorrido ::= instrucciones
        |recorrido instrucciones
;

instrucciones ::= declaracion
    | arreglos
    | funcionesgrafica
    | printarreglos
    | printexpresiones
    | error PUNTOYCOMA

;

funcionesgrafica ::= declaracionhistograma
    |declaracionbarras
    |declaracionpie
    |declaracionlinea
;

declaracion ::= VAR:var DOSPUNTOS tipodedato:td DOSPUNTOS DOSPUNTOS IDENTIFICADOR:id MENORQUE GUION  tipodato:tdd END PUNTOYCOMA {:funciones.reportes.TablaDatos(td.toString(),id.toString(),tdd,varright,varleft);:}
            |VAR:var DOSPUNTOS tipodedato:tp DOSPUNTOS DOSPUNTOS IDENTIFICADOR:id MENORQUE GUION  expresion:ex END PUNTOYCOMA    {:funciones.reportes.TablaDatos(tp.toString(),id.toString(),ex,varright,varleft);:}
;
tipodedato ::= R_DOUBLE:d {:RESULT=d;:}
        |R_CHAR:c CORCHETE_ABRE CORCHETE_CIERRA {:RESULT=c;:}
;

tipodato ::= DECIMAL:dec {:RESULT=dec;:}
        |CADENA:c {:RESULT=c;:}
        |ENTERO:e {:RESULT=e;:}
        |IDENTIFICADOR:id{:RESULT=funciones.reportes.busqueda(id);:}
        
;
//----------------------------------------IMPRESIONES

printarreglos ::= CONSOLE DOSPUNTOS DOSPUNTOS COLUMN IGUAL IDENTIFICADOR GUION MAYORQUE nt END PUNTOYCOMA{::}
        |CONSOLE DOSPUNTOS DOSPUNTOS COLUMN IGUAL CADENA GUION MAYORQUE nt END PUNTOYCOMA{::}
         
;
nt ::= ARROBA IDENTIFICADOR 
        |CORCHETE_ABRE elementos CORCHETE_CIERRA
;
printexpresiones ::= CONSOLE DOSPUNTOS DOSPUNTOS PRINT IGUAL ciclo END PUNTOYCOMA {::} 
;

ntexp ::= IDENTIFICADOR:ni {:RESULT=funciones.reportes.busqueda(ni);:}
        |CADENA:c {:RESULT=c;:}
        |ENTERO:e   {:RESULT=e;:}
        |DECIMAL:d  {:RESULT=d;:}
        |expresion:exp {:RESULT=exp;:}
        
;

ciclo ::= ntexp
        |ntexp COMA ciclo
;


//----------------------------------------GRAFICAS

declaracionlinea ::= GRAPHLINE PARENTESIS_A  instruccionlinea PARENTESIS_C END PUNTOYCOMA {::}   
;


declaracionbarras ::= GRAPHBAR PARENTESIS_A  instruccionbarras PARENTESIS_C END PUNTOYCOMA {::}   
;

instruccionbarras ::= instruccionbarras contenidobarras {::}
        |contenidobarras {::}
;
contenidobarras ::= TITULOX DOSPUNTOS DOSPUNTOS R_CHAR CORCHETE_ABRE CORCHETE_CIERRA IGUAL CADENA END PUNTOYCOMA {::}
        |TITULOY DOSPUNTOS DOSPUNTOS R_CHAR CORCHETE_ABRE CORCHETE_CIERRA IGUAL tipodato END PUNTOYCOMA 
        |TITULO DOSPUNTOS DOSPUNTOS R_CHAR CORCHETE_ABRE CORCHETE_CIERRA IGUAL CADENA END PUNTOYCOMA 
        |EJEX DOSPUNTOS DOSPUNTOS R_CHAR CORCHETE_ABRE CORCHETE_CIERRA IGUAL  CORCHETE_ABRE elementosejex CORCHETE_CIERRA END PUNTOYCOMA 
        |EJEY DOSPUNTOS DOSPUNTOS R_DOUBLE IGUAL CORCHETE_ABRE elementosejey CORCHETE_CIERRA END PUNTOYCOMA 
        |EXEC GRAPHBAR END PUNTOYCOMA
;

elementosejey::= valory {::}
        |elementosejey COMA valory {::}
;

valory ::= ENTERO
        |DECIMAL
        |IDENTIFICADOR
;
elementosejex::= datox {::}
        |elementosejex COMA datox {::}
;

datox ::= CADENA
        
;


declaracionhistograma ::= HISTOGRAM PARENTESIS_A  instruccionhistograma PARENTESIS_C END PUNTOYCOMA {::}       
;

instruccionhistograma ::= instruccionhistograma contenidohistograma {::}
        |contenidohistograma {::}
;

contenidohistograma ::= TITULO DOSPUNTOS DOSPUNTOS R_CHAR CORCHETE_ABRE CORCHETE_CIERRA IGUAL datosgraficas END PUNTOYCOMA {::}
        |VALUES DOSPUNTOS DOSPUNTOS R_CHAR CORCHETE_ABRE CORCHETE_CIERRA IGUAL datosgraficas END PUNTOYCOMA {::}
        |EXEC HISTOGRAM END PUNTOYCOMA {::}
;

elementoshistograma::= valorhistograma {::}
        |elementoshistograma COMA valorhistograma {::}
;

valorhistograma ::= ENTERO
        |DECIMAL
;




declaracionlinea ::= GRAPHLINE PARENTESIS_A PARENTESIS_C END PUNTOYCOMA   {::}
;

instruccionlinea ::= instruccionlinea contenidolinea {::}
        |contenidolinea {::}
;
contenidolinea ::= TITULO DOSPUNTOS DOSPUNTOS R_CHAR CORCHETE_ABRE CORCHETE_CIERRA IGUAL datosgraficas  END PUNTOYCOMA {::} 
        |EJEX DOSPUNTOS DOSPUNTOS R_CHAR CORCHETE_ABRE CORCHETE_CIERRA IGUAL   datosgraficas  END PUNTOYCOMA {::}
        |EJEY DOSPUNTOS DOSPUNTOS  R_DOUBLE IGUAL   datosgraficas  END PUNTOYCOMA {::}
        |TITULOX DOSPUNTOS DOSPUNTOS R_CHAR CORCHETE_ABRE CORCHETE_CIERRA IGUAL datosgraficas END PUNTOYCOMA{::}
        |TITULOY DOSPUNTOS DOSPUNTOS R_CHAR CORCHETE_ABRE  CORCHETE_CIERRA IGUAL datosgraficas END PUNTOYCOMA{::}

        |EXEC GRAPHLINE END PUNTOYCOMA {::}
;
elementoslinea::= valorlinea {::}
        |elementoslinea COMA valorlinea {::}
;

valorlinea ::= ENTERO
        |DECIMAL
;

elementoslineac::= datoslineac {::}
        |elementoslineac COMA datoslineac {::}
        |datosgraficas
;

datoslineac ::= CADENA
        
;





declaracionpie::= GRAPHPIE PARENTESIS_A instrucciongrafica PARENTESIS_C END PUNTOYCOMA   {::}
;


instrucciongrafica ::= instrucciongrafica contenidopie {::}
        |contenidopie {::}
;

contenidopie ::= TITULO DOSPUNTOS DOSPUNTOS R_CHAR CORCHETE_ABRE CORCHETE_CIERRA IGUAL CADENA  END PUNTOYCOMA {::} 
        |VALUES DOSPUNTOS DOSPUNTOS R_DOUBLE IGUAL CORCHETE_ABRE elementospie CORCHETE_CIERRA  END PUNTOYCOMA{::} 
        |LABEL DOSPUNTOS DOSPUNTOS R_CHAR CORCHETE_ABRE CORCHETE_CIERRA IGUAL CORCHETE_ABRE elementoslabel CORCHETE_CIERRA END PUNTOYCOMA{::}
        |EXEC GRAPHPIE END PUNTOYCOMA{::}
;
elementospie::= valorpie {::}
        |elementospie COMA valorpie {::}
;

valorpie ::= ENTERO
        |DECIMAL
;

elementoslabel::= datoslabel{::}
        |elementoslabel COMA datoslabel
;
datoslabel ::= CADENA {::}
;

//-------------------------------------ARREGLOS----------------------------------------------------------------

arreglos ::= ARR DOSPUNTOS tipodedato DOSPUNTOS DOSPUNTOS ARROBA IDENTIFICADOR MENORQUE GUION CORCHETE_ABRE elementos CORCHETE_CIERRA END PUNTOYCOMA{::}
;

elementos ::= valorexpresion {::}
        //|elementos COMA valor {::}
        |valorexpresion COMA elementos
;

valor ::= DECIMAL {::}
        |CADENA {::}
        |IDENTIFICADOR {::}
        |ENTERO {::}
;

//--------------------------OPERACIONES--------------------------------------


expresion ::= SUM PARENTESIS_A valorexpresion:a COMA valorexpresion:b PARENTESIS_C {:RESULT=Double.parseDouble(a.toString())+Double.parseDouble(b.toString());:}
            | RES PARENTESIS_A valorexpresion:a COMA valorexpresion:b PARENTESIS_C {:RESULT=Double.parseDouble(a.toString())-Double.parseDouble(b.toString());:}
            | MUL PARENTESIS_A valorexpresion:a COMA valorexpresion:b PARENTESIS_C {:RESULT=Double.parseDouble(a.toString())*Double.parseDouble(b.toString());:}
            | DIV PARENTESIS_A valorexpresion:a COMA valorexpresion:b PARENTESIS_C {:RESULT=Double.parseDouble(a.toString())/Double.parseDouble(b.toString());:}
            | MOD PARENTESIS_A valorexpresion:a COMA valorexpresion:b PARENTESIS_C {:RESULT=Double.parseDouble(a.toString())%Double.parseDouble(b.toString());:}  
            | operacionesnest
;

valorexpresion ::=  expresion:e {:RESULT=e;:}
        | DECIMAL:d {:RESULT=d;:}
        | IDENTIFICADOR {::}
        | ENTERO:entero {:RESULT=entero;:}
        | CADENA:charm   {:RESULT=charm;:}
        
        
;

operacionesnest ::= MEDIA PARENTESIS_A arregloexpresiones:arregloexp PARENTESIS_C {:RESULT=arregloexp;:}
        |MEDIANA  PARENTESIS_A arregloexpresiones:arregloexp PARENTESIS_C                    {:RESULT=arregloexp;:}
        |MODA     PARENTESIS_A  arregloexpresiones:arregloexp PARENTESIS_C                   {:RESULT=arregloexp;:}
        |VARIANZA PARENTESIS_A arregloexpresiones:arregloexp PARENTESIS_C                    {:RESULT=arregloexp;:}
        |MAX      PARENTESIS_A arregloexpresiones:arregloexp PARENTESIS_C                    {:RESULT=arregloexp;:}
        |MIN      PARENTESIS_A arregloexpresiones:arregloexp PARENTESIS_C                    {:RESULT=arregloexp;:}
;

arregloexpresiones ::= ARROBA:arroba IDENTIFICADOR:id{:RESULT=funciones.reportes.busqueda(arroba.toString()+id.toString());:}
        | CORCHETE_ABRE elementos:el CORCHETE_CIERRA {:RESULT=el;:}
;


datosgraficas ::= ENTERO:entero
        |DECIMAL:decimal
        |CADENA:cadena
        |arregloexpresiones:arregloexpresiones
        |IDENTIFICADOR:identificador
        
;