
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package DataForge_;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 19;
  public static final int POR = 11;
  public static final int PUNTOYCOMA = 4;
  public static final int RES = 7;
  public static final int ENTERO = 14;
  public static final int GRAPHPIE = 44;
  public static final int GRAPHBAR = 45;
  public static final int TITULOY = 50;
  public static final int TITULOX = 49;
  public static final int IDENTIFICADOR = 51;
  public static final int EJEY = 42;
  public static final int IGUAL = 53;
  public static final int EJEX = 41;
  public static final int MAYORQUE = 22;
  public static final int COLUMN = 36;
  public static final int CORCHETE_CIERRA = 25;
  public static final int ARROBA = 23;
  public static final int TITULO = 38;
  public static final int DIV = 9;
  public static final int GUION = 52;
  public static final int R_CHAR = 27;
  public static final int MIN = 34;
  public static final int MEDIANA = 30;
  public static final int EOF = 0;
  public static final int DECIMAL = 15;
  public static final int R_MOSTRAR = 13;
  public static final int error = 1;
  public static final int PROGRAM = 17;
  public static final int MUL = 8;
  public static final int COMA = 5;
  public static final int CADENA = 16;
  public static final int VALUES = 39;
  public static final int MODA = 31;
  public static final int MOD = 10;
  public static final int MENORQUE = 21;
  public static final int CORCHETE_ABRE = 24;
  public static final int GRAPPIE = 43;
  public static final int PARENTESIS_C = 3;
  public static final int PARENTESIS_A = 2;
  public static final int VARIANZA = 32;
  public static final int GRAPBAR = 54;
  public static final int R_DOUBLE = 26;
  public static final int END = 18;
  public static final int SUM = 6;
  public static final int ARR = 28;
  public static final int MEDIA = 29;
  public static final int EXEC = 37;
  public static final int LABEL = 40;
  public static final int MAX = 33;
  public static final int HISTOGRAM = 47;
  public static final int GRAPHLINE = 46;
  public static final int VAR = 20;
  public static final int GRAPLINE = 55;
  public static final int CONSOLE = 48;
  public static final int PRINT = 35;
  public static final int MAS = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "PUNTOYCOMA",
  "COMA",
  "SUM",
  "RES",
  "MUL",
  "DIV",
  "MOD",
  "POR",
  "MAS",
  "R_MOSTRAR",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "PROGRAM",
  "END",
  "DOSPUNTOS",
  "VAR",
  "MENORQUE",
  "MAYORQUE",
  "ARROBA",
  "CORCHETE_ABRE",
  "CORCHETE_CIERRA",
  "R_DOUBLE",
  "R_CHAR",
  "ARR",
  "MEDIA",
  "MEDIANA",
  "MODA",
  "VARIANZA",
  "MAX",
  "MIN",
  "PRINT",
  "COLUMN",
  "EXEC",
  "TITULO",
  "VALUES",
  "LABEL",
  "EJEX",
  "EJEY",
  "GRAPPIE",
  "GRAPHPIE",
  "GRAPHBAR",
  "GRAPHLINE",
  "HISTOGRAM",
  "CONSOLE",
  "TITULOX",
  "TITULOY",
  "IDENTIFICADOR",
  "GUION",
  "IGUAL",
  "GRAPBAR",
  "GRAPLINE"
  };
}

