
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package DataForge_;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 7;
  public static final int PUNTOYCOMA = 4;
  public static final int ARR = 21;
  public static final int DOSPUNTOS = 13;
  public static final int CORCHETE_CIERRA = 18;
  public static final int DECIMAL = 10;
  public static final int CORCHETE_ABRE = 17;
  public static final int END = 12;
  public static final int POR = 5;
  public static final int PROGRAM = 11;
  public static final int EOF = 0;
  public static final int MENORQUE = 15;
  public static final int R_CHAR = 20;
  public static final int PARENTESIS_C = 3;
  public static final int error = 1;
  public static final int PARENTESIS_A = 2;
  public static final int R_DOUBLE = 19;
  public static final int ENTERO = 9;
  public static final int ARROBA = 16;
  public static final int R_MOSTRAR = 8;
  public static final int MAS = 6;
  public static final int VAR = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "PUNTOYCOMA",
  "POR",
  "MAS",
  "MENOS",
  "R_MOSTRAR",
  "ENTERO",
  "DECIMAL",
  "PROGRAM",
  "END",
  "DOSPUNTOS",
  "VAR",
  "MENORQUE",
  "ARROBA",
  "CORCHETE_ABRE",
  "CORCHETE_CIERRA",
  "R_DOUBLE",
  "R_CHAR",
  "ARR"
  };
}

